- name: "Install GPG tool"
  apt:
    force: "yes"
    update_cache: "yes"
    name: "{{ item }}"
    state: "latest"
  loop:
  - "gnupg2"

- name: "Import InfluxDB GPG signing key"
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: "present"

- name: "Add InfluxDB repository"
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: "influxdb"
    state: "present"

- name: "Install InfluxDB and Telegraf"
  apt:
    force: "yes"
    update_cache: "yes"
    name: "{{ item }}"
    state: "latest"
  loop:
  - "telegraf"
  - "influxdb"
